"""Build the two figures cited by ``paper_a.tex``.

The horizon-wise values are generated by the leakage-free empirical rerun.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


MODELS = ("lightgbm", "sarima")
LABELS = {"lightgbm": "LightGBM", "sarima": "SARIMA"}
COLORS = {"lightgbm": "#2166ac", "sarima": "#b2182b"}
MARKERS = {"lightgbm": "o", "sarima": "s"}


def _series(frame: pd.DataFrame, model: str, column: str) -> tuple[np.ndarray, np.ndarray]:
    subset = frame.loc[frame["model"].eq(model)].sort_values("horizon")
    return subset["horizon"].to_numpy(), subset[column].to_numpy()


def _style_axis(axis: plt.Axes, horizons: list[int]) -> None:
    axis.set_xticks(horizons)
    axis.grid(True, alpha=0.22, linewidth=0.7)
    axis.spines[["top", "right"]].set_visible(False)
    axis.tick_params(labelsize=8)


def build_figure1(metrics: pd.DataFrame, output_dir: Path, dpi: int) -> None:
    horizons = sorted(metrics["horizon"].unique().tolist())
    figure, axes = plt.subplots(1, 2, figsize=(7.2, 3.25), constrained_layout=True)

    for model in MODELS:
        h, values = _series(metrics, model, "skill_rmse")
        axes[0].plot(h, values, color=COLORS[model], marker=MARKERS[model],
                     linewidth=1.8, markersize=5, label=LABELS[model])
    axes[0].axhline(0, color="0.45", linestyle="--", linewidth=1)
    axes[0].set(title="(A) Persistence-relative RMSE skill",
                xlabel="Forecast horizon (h)", ylabel="Skill")
    axes[0].set_ylim(-0.12, 0.16)
    axes[0].legend(frameon=False, fontsize=8)
    _style_axis(axes[0], horizons)

    for model in MODELS:
        h, values = _series(metrics, model, "variance_retention_pct")
        axes[1].plot(h, values, color=COLORS[model], marker=MARKERS[model],
                     linewidth=1.8, markersize=5, label=LABELS[model])
    axes[1].axhline(100, color="0.45", linestyle="--", linewidth=1,
                    label="Full variance")
    axes[1].set(title="(B) Variance retention",
                xlabel="Forecast horizon (h)", ylabel="Variance retention (%)")
    axes[1].set_ylim(0, 108)
    axes[1].legend(frameon=False, fontsize=8)
    _style_axis(axes[1], horizons)

    for suffix in ("png", "pdf"):
        figure.savefig(output_dir / f"figure1_skill_variance.{suffix}", dpi=dpi,
                       bbox_inches="tight")
    plt.close(figure)


def build_figure2(
    metrics: pd.DataFrame,
    events: pd.DataFrame,
    output_dir: Path,
    dpi: int,
) -> None:
    horizons = sorted(metrics["horizon"].unique().tolist())
    figure, axes = plt.subplots(1, 2, figsize=(7.8, 3.25), constrained_layout=True)

    for model in MODELS:
        h, values = _series(metrics, model, "skill_vp")
        axes[0].plot(h, values, color=COLORS[model], marker=MARKERS[model],
                     linewidth=1.8, markersize=5, label=LABELS[model])
    axes[0].axhline(0, color="0.45", linestyle="--", linewidth=1)
    axes[0].set(title=r"(C) Diagnostic Skill$_{VP}$",
                xlabel="Forecast horizon (h)", ylabel=r"Skill$_{VP}$")
    axes[0].set_ylim(-0.08, 0.05)
    axes[0].legend(frameon=False, fontsize=8)
    _style_axis(axes[0], horizons)

    for model in MODELS:
        subset = events.loc[events["model"].eq(model)].sort_values("horizon")
        axes[1].plot(subset["horizon"], subset["recall"], color=COLORS[model],
                     marker=MARKERS[model], linewidth=1.8,
                     label=f"{LABELS[model]} recall")
        axes[1].plot(subset["horizon"], subset["precision"], color=COLORS[model],
                     marker=MARKERS[model], linewidth=1.4, linestyle="--",
                     label=f"{LABELS[model]} precision")
    axes[1].set(title="(D) P75 event metrics", xlabel="Forecast horizon (h)",
                ylabel="Metric value")
    axes[1].set_xticks(horizons)
    axes[1].set_ylim(0, 1.0)
    axes[1].grid(True, axis="y", alpha=0.22, linewidth=0.7)
    axes[1].spines[["top", "right"]].set_visible(False)
    axes[1].tick_params(labelsize=8)
    axes[1].legend(frameon=False, fontsize=7, loc="best")

    for suffix in ("png", "pdf"):
        figure.savefig(output_dir / f"figure2_skillvp_events.{suffix}", dpi=dpi,
                       bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metrics", type=Path,
                        default=Path("outputs/reproduction/metrics_rolling_origin.csv"))
    parser.add_argument("--events", type=Path,
                        default=Path("outputs/reproduction/events_p75_rolling_origin.csv"))
    parser.add_argument("--output-dir", type=Path,
                        default=Path("outputs/figures"))
    parser.add_argument("--dpi", type=int, default=300)
    args = parser.parse_args()

    metrics = pd.read_csv(args.metrics)
    events = pd.read_csv(args.events)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    build_figure1(metrics, args.output_dir, args.dpi)
    build_figure2(metrics, events, args.output_dir, args.dpi)


if __name__ == "__main__":
    main()
